[package]
name = "dcb-bytes-derive"
version = "0.1.0"
authors = ["Filipe Rodrigues <filipejacintorodrigues1@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.8"
syn = { version = "1.0.58", features = ["full", "extra-traits"] }
